[WIP]Viewmarkup
kenta-hiraoka/chat-space pull request #2
Opened 2019-02-18 08:35 UTC by kenta-hiraoka

# WHAT
chat-spaceのビュー画面の実装をする。

# WHY
アプリケーションの機能に必要不可欠なため。

2019-02-18 08:38 UTC, kenta-hiraoka commented
<img width="1437" alt="85441fbe5439c53a93dc4b3b83e6ea90" src="https://user-images.githubusercontent.com/38944204/52937985-d784c800-33a3-11e9-8ffc-25d4fe5a44f7.png">

2019-02-18 08:45 UTC, ghost requested changes

2019-02-18 08:45 UTC, hiroki5123 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
ここのコメントアウト消しちゃって大丈夫です

2019-02-18 08:45 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        = link_to "" do
ここはlink_toを仕様しません。
```input type="file"```
で実装してください

2019-02-18 08:45 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        EDIT
こちらはリンクにしてください。

2019-02-18 08:45 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    .side-bar
ここからyieldの手前までを部分テンプレートで切り出して読み込んでください。

2019-02-19 03:01 UTC, kenta-hiraoka commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
修正しました。

2019-02-19 03:01 UTC, kenta-hiraoka commented on app/views/messages/index.html.haml
> +        = link_to "" do
修正しました。

2019-02-19 03:01 UTC, kenta-hiraoka commented on app/views/messages/index.html.haml
> +        EDIT
修正しました。

2019-02-19 03:01 UTC, kenta-hiraoka commented on app/views/layouts/application.html.haml
> +    .side-bar
指摘いただいた部分を部分テンプレートにし、_side-bar.html.hamlに移しました。

2019-02-19 03:05 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
>      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう

2019-02-19 03:05 UTC, TOMARUMARU commented on app/views/messages/index.html.haml
> +      %input{:type => "submit", :value => "SEND"}
ここら辺も

2019-02-19 05:11 UTC, kenta-hiraoka commented on app/views/layouts/application.html.haml
>      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
修正しました。

2019-02-19 05:11 UTC, kenta-hiraoka commented on app/views/messages/index.html.haml
> +      %input{:type => "submit", :value => "SEND"}
修正しました。

2019-02-19 05:14 UTC, miyagit approved these changes
LGTMです。

2019-02-27 06:10 UTC, merged