Asynchronous
kenta-hiraoka/chat-space pull request #7
Opened 2019-03-01 02:42 UTC by kenta-hiraoka

# WHAT
非同期通信機能を実装する

# アプリケーションに必要な為

2019-03-01 02:45 UTC, yusukeyamane commented
動作確認がしたいので、動作している様子をgifでお願いします！

2019-03-01 02:47 UTC, yusukeyamane commented
imageがない状態で送信しても問題なく送信できるか確認も一緒にお願いします

2019-03-01 02:47 UTC, yusukeyamane commented on app/controllers/messages_controller.rb
> +        format.html {redirect_to group_messages_path(@group), {notice: 'メッセージが送信されました'}}
今後は非同期のみで送信することになるので、こちらの記述は消しておきましょう

2019-03-01 02:47 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +      $('.form__message').val('')
reset()メソッドを使いましょう

2019-03-05 07:28 UTC, kenta-hiraoka commented
https://gyazo.com/7bbda4f5a5a63eebdb12bd9fe51af88d

2019-03-05 07:28 UTC, kenta-hiraoka commented on app/controllers/messages_controller.rb
> +        format.html {redirect_to group_messages_path(@group), {notice: 'メッセージが送信されました'}}
修正しました。

2019-03-05 07:28 UTC, kenta-hiraoka commented on app/assets/javascripts/message.js
> +      $('.form__message').val('')
reset()メソッドを使用しました

2019-03-05 07:30 UTC, ghost requested changes

2019-03-05 07:30 UTC, hiroki5123 commented on app/views/messages/_chat_content.html.haml
>    %ul
ulの直下はliである必要があります。

2019-03-05 07:47 UTC, kenta-hiraoka commented on app/views/messages/_chat_content.html.haml
>    %ul
修正しました。

2019-03-05 07:48 UTC, hiroki5123 commented
GIF見たのですが、再読み込みのボタンを押してメッセージが反映されているように見えます。
再読み込みのボタンを押さずに、メッセージが追加されるようにしてください。

2019-03-05 08:06 UTC, kenta-hiraoka commented
以前記述をしないよう指摘を受けた部分なのですがこの部分を記述するとページを更新せずに投稿ができています。
他の部分で該当箇所があればご指摘いただきたいです。

2019-03-05 08:09 UTC, hiroki5123 commented on app/views/messages/_chat_content.html.haml
>    %ul
```
%li.message
  .message_name sample_name
  .time 2019/2/16 00:00:00
```

こんな感じで

2019-03-05 08:09 UTC, hiroki5123 commented
> 以前記述をしないよう指摘を受けた部分なのですがこの部分を

どこの部分をさしていますか？

2019-03-05 08:34 UTC, kenta-hiraoka commented
https://gyazo.com/748719313432eb75cd0dc6a94aab4700

この部分なのですが、今確認したところ
投稿の1回目はHTML側が動く（フラッシュメッセージがでる）
2回目以降は更新ボタンを押さないと投稿が反映されない
という状態になっていました。

2019-03-05 08:54 UTC, ReoKuriyama commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path, flash: { notice: "送信されました" } }
html形式でのレスポンスは使用しないので削除してください。
これで非同期通信がうまくいっているかどうかが一目でわかるかと思います。

2019-03-05 10:29 UTC, kenta-hiraoka commented
https://gyazo.com/41f05d5b7b02f0f541e5390c07f8ba91

html形式の記述を消し、投稿できるようにしました。

2019-03-05 10:33 UTC, ghost requested changes

2019-03-05 10:33 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    }
54行目の下に
```$('.form_submit').prop('disabled', false);```
を入れれば共通化出来ます

2019-03-05 11:20 UTC, kenta-hiraoka commented
58行目に
$('.form_submit').prop('disabled', false);
を記述しました。

2019-03-05 11:22 UTC, ghost approved these changes
LGTMです！

2019-03-06 10:13 UTC, merged