Autoupdate
kenta-hiraoka/chat-space pull request #9
Opened 2019-03-08 11:17 UTC by kenta-hiraoka

# WHAT
自動更新機能を実装する

# WHY
チャット利用をよりスムーズに行うため

2019-03-08 11:19 UTC, kenta-hiraoka commented
https://gyazo.com/47a6b726ba09b5c754876fb708044f81

2019-03-08 11:21 UTC, yuki-uchida requested changes

2019-03-08 11:21 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> -  })
これより上が差分として出てきておらず、確認ができません。
間違えてmasterにpushしてはいませんか？
まずはmasterにrevert処理をかけ、今回のプルリクの変更点がきちんと差分として確認できるようにしてください

2019-03-08 11:21 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +        .done(function(data) {
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-03-10 08:18 UTC, kenta-hiraoka commented on app/assets/javascripts/message.js
> -  })
返すHTML要素が同じなので、message.js内の下部に変更を加えています。

2019-03-10 08:18 UTC, kenta-hiraoka commented on app/assets/javascripts/message.js
> +        .done(function(data) {
new_messageに変更しました。

2019-03-10 08:21 UTC, kenta-hiraoka commented
https://gyazo.com/1d4494d7e630e98552ee15fac4cd4b9b

2019-03-10 08:24 UTC, ghost approved these changes
LGTMです!

2019-03-10 08:37 UTC, merged